services:
#    aoshidoweb.example:
#        class: Aoshido\webBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    my.subscriber:
        class: Aoshido\webBundle\form\EventListener\AddTemaByMateriaFieldSuscriber 
        arguments:
            - @doctrine.orm.entity_manager
            
    my.form:
        class: Aoshido\webBundle\form\PreguntaType